#pragma once

#define CURRENT_TRANSACTION_VERSION      1
#define HF_VERSION_ENABLE_N_OUTS         2
#define TRANSACTION_VERSION_N_OUTS       3
#define TRANSACTION_VERSION_CARROT       4
#define TRANSACTION_VERSION_ENABLE_TOKENS 5

// UNLOCK TIMES

#define PRICING_RECORD_VALID_TIME_DIFF_FROM_BLOCK       120  // seconds

enum BLOB_TYPE {
  BLOB_TYPE_CRYPTONOTE        = 0,
  BLOB_TYPE_FORKNOTE1         = 1,
  BLOB_TYPE_FORKNOTE2         = 2,
  BLOB_TYPE_CRYPTONOTE2       = 3, // Masari
  BLOB_TYPE_CRYPTONOTE_RYO    = 4, // Ryo
  BLOB_TYPE_CRYPTONOTE_LOKI   = 5, // Loki
  BLOB_TYPE_CRYPTONOTE3       = 6, // Masari
  BLOB_TYPE_AEON              = 7, // Aeon
  BLOB_TYPE_CRYPTONOTE_CUCKOO = 8, // MoneroV / Swap
  BLOB_TYPE_CRYPTONOTE_XTNC   = 9, // XTNC
  BLOB_TYPE_CRYPTONOTE_TUBE   = 10, // TUBE
  BLOB_TYPE_CRYPTONOTE_XTA    = 12, // ITALO
  BLOB_TYPE_CRYPTONOTE_ZEPHYR = 13, // ZEPHYR
  BLOB_TYPE_CRYPTONOTE_XLA    = 14, // XLA
  BLOB_TYPE_CRYPTONOTE_SALVIUM= 15, // Salvium
  BLOB_TYPE_CRYPTONOTE_ARQMA  = 16  // Arqma
};

inline bool is_supported_blob_type(enum BLOB_TYPE blob_type) {
  switch (blob_type) {
    case BLOB_TYPE_CRYPTONOTE:
    case BLOB_TYPE_FORKNOTE1:
    case BLOB_TYPE_FORKNOTE2:
    case BLOB_TYPE_CRYPTONOTE2:
    case BLOB_TYPE_CRYPTONOTE_RYO:
    case BLOB_TYPE_CRYPTONOTE_LOKI:
    case BLOB_TYPE_CRYPTONOTE3:
    case BLOB_TYPE_AEON:
    case BLOB_TYPE_CRYPTONOTE_CUCKOO:
    case BLOB_TYPE_CRYPTONOTE_XTNC:
    case BLOB_TYPE_CRYPTONOTE_TUBE:
    case BLOB_TYPE_CRYPTONOTE_XTA:
    case BLOB_TYPE_CRYPTONOTE_ZEPHYR:
    case BLOB_TYPE_CRYPTONOTE_XLA:
    case BLOB_TYPE_CRYPTONOTE_SALVIUM:
    case BLOB_TYPE_CRYPTONOTE_ARQMA:
      return true;
    default:
      return false;
  }
}
